name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_call:
    # Allow this workflow to be called by other workflows

env:
  GO_VERSION: '1.24'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race ./...

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test -v -race -coverprofile=coverage/coverage.out ./...
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage/
          retention-days: 30

